#!/bin/bash
#PBS -l walltime=00:30:00 # Set whatever wall time you would like
#PBS -l nodes=1:ppn=12 # NOTE: ppn should be equal to 'n_proc' in 'run.py'
#PBS -N {JOB_NAME} # Replace {JOB_NAME} with a meaningful name
#PBS -q secondary # Set job queue name
#PBS -m be
# End of embedded QSUB options

# Load module 
module load {MODULE_NAME} # Replace {MODULE_NAME} with whatever module(s) you will need to load, if there is any.

# Run code
python {PATH_OF_RUN_CODE}/run.py
